"""Tests for the Codex adapter: detection, hooks, the command rule, and the Stop response."""

import json
from pathlib import Path

import pytest

from pskill_runner.adapters import adapter_for, detect_harness
from pskill_runner.codex import (
    HOOKS_RELATIVE_PATH,
    PROJECT_ROOT_CODE,
    RULES_RELATIVE_PATH,
    stop_response,
    sync_codex_settings,
)
from pskill_runner.hook_settings import SettingsError, hook_command


def read_hooks(root: Path) -> dict[str, object]:
    return dict(json.loads((root / HOOKS_RELATIVE_PATH).read_text(encoding="utf-8")))


def hook_commands(settings: dict[str, object], event: str) -> list[str]:
    hooks = settings["hooks"]
    assert isinstance(hooks, dict)
    return [handler["command"] for group in hooks.get(event, []) for handler in group["hooks"]]


def test_codex_is_detected_from_its_thread_id_variable() -> None:
    assert detect_harness({"CODEX_THREAD_ID": "019a-thread"}) == "codex"
    assert detect_harness({"CLAUDECODE": "1", "CODEX_THREAD_ID": "x"}) == "claude-code"


def test_the_codex_adapter_names_its_spawn_tool_and_asks_in_chat() -> None:
    adapter = adapter_for("codex")

    assert adapter.can_spawn_subagents is True
    assert "spawn_agent" in adapter.subagent_wording
    assert "chat" in adapter.question_wording


def test_sync_adds_the_two_hooks_resolved_from_the_git_root(tmp_path: Path) -> None:
    changed = sync_codex_settings(tmp_path, check_only=False)

    settings = read_hooks(tmp_path)
    assert changed is True
    assert hook_commands(settings, "Stop") == [hook_command(PROJECT_ROOT_CODE, "stop", "codex")]
    assert hook_commands(settings, "SessionStart") == [hook_command(PROJECT_ROOT_CODE, "session-start", "codex")]


def test_sync_writes_the_command_rule(tmp_path: Path) -> None:
    sync_codex_settings(tmp_path, check_only=False)

    rules = (tmp_path / RULES_RELATIVE_PATH).read_text(encoding="utf-8")
    assert 'pattern = ["uv", "run", ".pskill/pskill.py"]' in rules
    assert 'decision = "allow"' in rules
    assert "Generated by pskill" in rules


def test_sync_is_idempotent_and_keeps_foreign_hooks(tmp_path: Path) -> None:
    (tmp_path / ".codex").mkdir()
    foreign = {"hooks": {"Stop": [{"hooks": [{"type": "command", "command": "./notify.sh"}]}]}}
    (tmp_path / HOOKS_RELATIVE_PATH).write_text(json.dumps(foreign), encoding="utf-8")
    sync_codex_settings(tmp_path, check_only=False)

    assert sync_codex_settings(tmp_path, check_only=False) is False
    assert hook_commands(read_hooks(tmp_path), "Stop")[0] == "./notify.sh"


def test_check_only_reports_without_writing(tmp_path: Path) -> None:
    assert sync_codex_settings(tmp_path, check_only=True) is True
    assert not (tmp_path / ".codex").exists()


def test_a_hooks_file_that_does_not_parse_is_never_overwritten(tmp_path: Path) -> None:
    (tmp_path / ".codex").mkdir()
    (tmp_path / HOOKS_RELATIVE_PATH).write_text("{ broken", encoding="utf-8")

    with pytest.raises(SettingsError, match="not valid JSON"):
        sync_codex_settings(tmp_path, check_only=False)


def test_a_blocking_stop_response_is_a_decision_with_the_reason() -> None:
    stdout, exit_code = stop_response("Continue the run.")

    assert exit_code == 0
    assert json.loads(stdout) == {"decision": "block", "reason": "Continue the run."}


def test_an_allowing_stop_response_is_still_json() -> None:
    stdout, exit_code = stop_response(None)

    assert (json.loads(stdout), exit_code) == ({}, 0)
