"""Tests for the Codex adapter: detection, hooks, the command rule, and the Stop response."""

import json
from pathlib import Path

import pytest

from pskill_runner.adapters import TierRow, adapter_for, detect_harness
from pskill_runner.codex import (
    HOOKS_RELATIVE_PATH,
    PROJECT_ROOT_CODE,
    PSKILL_HOOKS,
    RULES_RELATIVE_PATH,
    codex_home,
    read_model_catalog,
    stop_response,
    sync_codex_rules,
    tier_model_problems,
)
from pskill_runner.hook_settings import SettingsError, hook_command, sync_hook_file


def sync_codex_settings(root: Path, check_only: bool) -> bool:
    """What the default sync does for Codex: its hooks, and its command rule."""
    hooks_changed = sync_hook_file(root / HOOKS_RELATIVE_PATH, PSKILL_HOOKS, check_only)
    return sync_codex_rules(root, check_only) or hooks_changed


def read_hooks(root: Path) -> dict[str, object]:
    return dict(json.loads((root / HOOKS_RELATIVE_PATH).read_text(encoding="utf-8")))


def hook_commands(settings: dict[str, object], event: str) -> list[str]:
    hooks = settings["hooks"]
    assert isinstance(hooks, dict)
    return [handler["command"] for group in hooks.get(event, []) for handler in group["hooks"]]


def test_codex_is_detected_from_its_thread_id_variable() -> None:
    assert detect_harness({"CODEX_THREAD_ID": "019a-thread"}) == "codex"
    assert detect_harness({"CLAUDECODE": "1", "CODEX_THREAD_ID": "x"}) == "claude-code"


def test_the_codex_adapter_names_its_spawn_tool_and_asks_in_chat() -> None:
    adapter = adapter_for("codex")

    assert adapter.can_spawn_subagents is True
    assert "spawn_agent" in adapter.subagent_wording
    assert "chat" in adapter.question_wording


def test_sync_adds_the_two_hooks_resolved_from_the_git_root(tmp_path: Path) -> None:
    changed = sync_codex_settings(tmp_path, check_only=False)

    settings = read_hooks(tmp_path)
    assert changed is True
    assert hook_commands(settings, "Stop") == [hook_command(PROJECT_ROOT_CODE, "stop", "codex")]
    assert hook_commands(settings, "SessionStart") == [hook_command(PROJECT_ROOT_CODE, "session-start", "codex")]


def test_sync_writes_the_command_rule(tmp_path: Path) -> None:
    sync_codex_settings(tmp_path, check_only=False)

    rules = (tmp_path / RULES_RELATIVE_PATH).read_text(encoding="utf-8")
    assert 'pattern = ["uv", "run", ".pskill/pskill.py"]' in rules
    assert 'decision = "allow"' in rules
    assert "Generated by pskill" in rules


def test_the_command_rule_asks_before_a_runner_update_or_install(tmp_path: Path) -> None:
    """`update --from <url>` could pin any code. The strictest matching rule wins, so Codex asks first."""
    sync_codex_settings(tmp_path, check_only=False)

    rules = (tmp_path / RULES_RELATIVE_PATH).read_text(encoding="utf-8")
    assert 'pattern = ["uv", "run", ".pskill/pskill.py", ["update", "init"]]' in rules
    assert 'decision = "prompt"' in rules
    assert '"uv run .pskill/pskill.py update --from=https://example.com/pskill.zip"' in rules


def test_sync_is_idempotent_and_keeps_foreign_hooks(tmp_path: Path) -> None:
    (tmp_path / ".codex").mkdir()
    foreign = {"hooks": {"Stop": [{"hooks": [{"type": "command", "command": "./notify.sh"}]}]}}
    (tmp_path / HOOKS_RELATIVE_PATH).write_text(json.dumps(foreign), encoding="utf-8")
    sync_codex_settings(tmp_path, check_only=False)

    assert sync_codex_settings(tmp_path, check_only=False) is False
    assert hook_commands(read_hooks(tmp_path), "Stop")[0] == "./notify.sh"


def test_check_only_reports_without_writing(tmp_path: Path) -> None:
    assert sync_codex_settings(tmp_path, check_only=True) is True
    assert not (tmp_path / ".codex").exists()


def test_a_hooks_file_that_does_not_parse_is_never_overwritten(tmp_path: Path) -> None:
    (tmp_path / ".codex").mkdir()
    (tmp_path / HOOKS_RELATIVE_PATH).write_text("{ broken", encoding="utf-8")

    with pytest.raises(SettingsError, match="not valid JSON"):
        sync_codex_settings(tmp_path, check_only=False)


def test_a_blocking_stop_response_is_a_decision_with_the_reason() -> None:
    stdout, exit_code = stop_response("Continue the run.")

    assert exit_code == 0
    assert json.loads(stdout) == {"decision": "block", "reason": "Continue the run."}


def test_an_allowing_stop_response_is_still_json() -> None:
    stdout, exit_code = stop_response(None)

    assert (json.loads(stdout), exit_code) == ({}, 0)


def write_catalog(codex_folder: Path, models: object) -> Path:
    codex_folder.mkdir(parents=True, exist_ok=True)
    path = codex_folder / "models_cache.json"
    path.write_text(json.dumps({"fetched_at": "2026-10-10T08:00:00Z", "models": models}), encoding="utf-8")
    return path


CATALOG_MODELS = [
    {"slug": "gpt-6-sol", "visibility": "list", "upgrade": None},
    {"slug": "gpt-6-luna", "visibility": "list", "upgrade": None},
    {"slug": "gpt-5.5", "upgrade": {"model": "gpt-6-sol", "migration_markdown": "Meet GPT-6 Sol"}},
]


def test_the_codex_folder_follows_codex_home(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(Path, "home", lambda: tmp_path / "home")

    assert codex_home({"CODEX_HOME": str(tmp_path / "codex")}) == tmp_path / "codex"
    assert codex_home({"CODEX_HOME": ""}) == tmp_path / "home" / ".codex"
    assert codex_home({}) == tmp_path / "home" / ".codex"


def test_the_codex_folder_reads_the_real_environment_by_default(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("CODEX_HOME", "/somewhere/codex")

    assert codex_home() == Path("/somewhere/codex")


def test_the_model_catalog_maps_each_model_to_its_upgrade(tmp_path: Path) -> None:
    path = write_catalog(tmp_path, [*CATALOG_MODELS, {"slug": 7}, "gpt-4", {"slug": "odd", "upgrade": "gpt-6"}])

    assert read_model_catalog(path) == {"gpt-6-sol": None, "gpt-6-luna": None, "gpt-5.5": "gpt-6-sol", "odd": None}


@pytest.mark.parametrize("text", ["not json", "[1, 2]", '{"models": {"slug": "gpt-6-sol"}}', "\udcff"])
def test_a_model_catalog_that_cannot_be_read_is_no_catalog(tmp_path: Path, text: str) -> None:
    path = tmp_path / "models_cache.json"
    path.write_text(text, encoding="utf-8", errors="surrogateescape")

    assert read_model_catalog(path) is None


def test_a_missing_model_catalog_is_no_catalog(tmp_path: Path) -> None:
    assert read_model_catalog(tmp_path / "models_cache.json") is None


def test_a_codex_tier_model_missing_from_the_catalog_or_with_an_upgrade_is_a_warning(tmp_path: Path) -> None:
    write_catalog(tmp_path, CATALOG_MODELS)
    tiers = {
        "codex": {
            "fast": TierRow(model="gpt-6-luna", effort="low"),
            "standard": TierRow(model="gpt-6.1-sol"),
            "deep": TierRow(model="gpt-5.5"),
        },
        "claude-code": {"fast": TierRow(model="haiku")},
    }

    problems = tier_model_problems(tiers, {"CODEX_HOME": str(tmp_path)})

    assert [(problem.level, problem.location) for problem in problems] == [
        ("warning", "tiers.codex.standard"),
        ("warning", "tiers.codex.deep"),
    ]
    assert "'gpt-6.1-sol' is not in the Codex model catalog" in problems[0].message
    assert "'gpt-5.5' has an upgrade to 'gpt-6-sol'" in problems[1].message


def test_codex_tier_models_are_not_checked_without_a_catalog(tmp_path: Path) -> None:
    tiers = {"codex": {"fast": TierRow(model="gpt-6-luna")}}

    assert tier_model_problems(tiers, {"CODEX_HOME": str(tmp_path)}) == []


def test_a_codex_row_without_a_model_is_not_checked(tmp_path: Path) -> None:
    write_catalog(tmp_path, CATALOG_MODELS)

    assert tier_model_problems({"codex": {"fast": TierRow(effort="low")}}, {"CODEX_HOME": str(tmp_path)}) == []
