"""Stubs: the generated, read-only SKILL.md files that make each skill visible to harnesses (SPEC.md 9.3).

A stub holds only the skill's name, description, inputs, and the command that starts a run. The real
skill stays in `.pskill/skills/`. `sync` writes one stub per skill into every folder in
`config.stub_folders`, and never touches a file without the generated marker.
"""

import json
from dataclasses import dataclass
from pathlib import Path

from pskill_runner.project import Project
from pskill_runner.skill_model import Skill, SkillCatalog

GENERATED_MARKER = "<!-- Generated by pskill. Do not edit. Run: uv run .pskill/pskill.py sync -->"
STUB_FILE_NAME = "SKILL.md"
RUNNER = "uv run .pskill/pskill.py"
PSKILL_STUB_NAME = "pskill"


class StubError(Exception):
    """A stub cannot be written without overwriting a hand-written skill."""


@dataclass(frozen=True)
class StubChange:
    path: Path
    action: str  # "created", "updated", or "deleted"


def render_stub(skill: Skill) -> str:
    frontmatter = [f"name: {skill.id}", f"description: {json.dumps(' '.join(skill.description.split()))}"]
    if skill.invocation == "manual":
        frontmatter.append("disable-model-invocation: true")
    input_lines = [
        f"   - `{name}` ({spec.type}{', optional' if spec.optional else ''}): {spec.description or ''}".rstrip()
        for name, spec in skill.inputs.items()
    ]
    input_options = " ".join(f"--input {name}=<value>" for name in skill.inputs)
    start_command = f"{RUNNER} start {skill.id} --harness auto {input_options}".rstrip()
    body = [
        GENERATED_MARKER,
        f"Source: `.pskill/skills/{skill.id}/`. This is a programmatic skill: the pskill runner controls its steps.",
        "",
        "1. Map the request to the inputs:" if input_lines else "1. This skill has no inputs.",
        *input_lines,
        f"2. Run: `{start_command}`",
        "   If a value has spaces, quotes, or several lines, pass `--inputs -` and give the inputs as YAML on stdin,",
        "   in the same literal form that the runner's packets show for `submit`.",
        "   Add `--mode autonomous` only when the user asked for no questions.",
        "3. Follow each packet that the runner prints until it says the run is finished.",
    ]
    return "---\n" + "\n".join(frontmatter) + "\n---\n" + "\n".join(body) + "\n"


def render_pskill_stub() -> str:
    """The built-in stub that helps the agent find, resume, and stop runs."""
    return "\n".join(
        [
            "---",
            f"name: {PSKILL_STUB_NAME}",
            'description: "Resume, inspect, pause, or cancel a pskill run (a programmatic skill run). Use when the '
            'user mentions an unfinished skill run, or asks which runs exist."',
            "---",
            GENERATED_MARKER,
            "Commands of the pskill runner:",
            f"- List the unfinished runs: `{RUNNER} runs --open`",
            f"- Show the current block of a run again: `{RUNNER} current <run-id>`",
            f"- Resume a paused run: `{RUNNER} resume <run-id>`",
            f"- Pause a run: `{RUNNER} pause <run-id>`",
            f"- Stop a run for good: `{RUNNER} cancel <run-id>`",
            f"- Open the run viewer: `{RUNNER} view`",
            "",
        ]
    )


def wanted_stubs(catalog: SkillCatalog) -> dict[str, str]:
    """Stub name -> stub text, for every skill that gets a stub, plus the pskill stub."""
    stubs = {skill.id: render_stub(skill) for skill in catalog.skills.values() if skill.invocation != "internal"}
    stubs[PSKILL_STUB_NAME] = render_pskill_stub()
    return stubs


def is_generated(path: Path) -> bool:
    return path.is_file() and GENERATED_MARKER in path.read_text(encoding="utf-8")


def sync_stubs(
    project: Project, catalog: SkillCatalog, check_only: bool, protected_names: set[str] | None = None
) -> list[StubChange]:
    """Bring every stub folder in line with the skills. With check_only, report the changes only.

    `protected_names` are skills that exist but do not load right now (for example a half-edited
    skill.yaml): their stubs are neither updated nor deleted.
    """
    stubs = wanted_stubs(catalog)
    changes: list[StubChange] = []
    for folder_name in project.config.stub_folders:
        folder = project.root / folder_name
        changes += stub_folder_changes(folder, stubs, protected_names or set())
    if not check_only:
        apply_stub_changes(changes, stubs)
    return changes


def stub_folder_changes(folder: Path, stubs: dict[str, str], protected_names: set[str]) -> list[StubChange]:
    changes = []
    for name, text in stubs.items():
        path = folder / name / STUB_FILE_NAME
        if not path.exists():
            changes.append(StubChange(path, "created"))
        elif not is_generated(path):
            raise StubError(f"{path} is a hand-written skill with the same name as a pskill skill. Rename one of them.")
        elif path.read_text(encoding="utf-8") != text:
            changes.append(StubChange(path, "updated"))
    if folder.is_dir():
        for path in sorted(folder.glob(f"*/{STUB_FILE_NAME}")):
            if path.parent.name not in stubs and path.parent.name not in protected_names and is_generated(path):
                changes.append(StubChange(path, "deleted"))
    return changes


def apply_stub_changes(changes: list[StubChange], stubs: dict[str, str]) -> None:
    for change in changes:
        if change.action == "deleted":
            change.path.unlink()
            if not any(change.path.parent.iterdir()):
                change.path.parent.rmdir()
            continue
        change.path.parent.mkdir(parents=True, exist_ok=True)
        change.path.write_text(stubs[change.path.parent.name], encoding="utf-8", newline="\n")
