"""Stubs: the generated, read-only SKILL.md files that make each skill visible to harnesses (SPEC.md 9.3).

A stub holds only the skill's name, description, inputs, and the command that starts a run. The real
skill stays in `.pskill/skills/`. `sync` writes one stub per skill into every folder in
`config.stub_folders`, and never touches a file without the generated marker.
"""

import json
from dataclasses import dataclass
from pathlib import Path

from pskill_runner.project import Project
from pskill_runner.skill_model import Skill, SkillCatalog

GENERATED_MARKER_TEXT = "Generated by pskill. Do not edit. Run: uv run .pskill/pskill.py sync"
GENERATED_MARKER = f"<!-- {GENERATED_MARKER_TEXT} -->"
STUB_FILE_NAME = "SKILL.md"
RUNNER = "uv run .pskill/pskill.py"
PSKILL_STUB_NAME = "pskill"
# Codex reads this file next to a skill: it stops the agent from starting a `manual` skill by itself.
SIDECAR_RELATIVE_PATH = "agents/openai.yaml"
SIDECAR_TEXT = f"# {GENERATED_MARKER_TEXT}\npolicy:\n  allow_implicit_invocation: false\n"


class StubError(Exception):
    """A stub cannot be written without overwriting a hand-written skill."""


@dataclass(frozen=True)
class StubChange:
    path: Path
    action: str  # "created", "updated", or "deleted"
    skill: str  # the stub's skill id (the name of its folder)


def render_stub(skill: Skill) -> str:
    frontmatter = [f"name: {skill.id}", f"description: {json.dumps(' '.join(skill.description.split()))}"]
    if skill.invocation == "manual":
        frontmatter.append("disable-model-invocation: true")
    input_lines = [
        f"   - `{name}` ({spec.type}{', optional' if spec.optional else ''}): {spec.description or ''}".rstrip()
        for name, spec in skill.inputs.items()
    ]
    input_options = " ".join(f"--input {name}=<value>" for name in skill.inputs)
    start_command = f"{RUNNER} start {skill.id} --harness auto {input_options}".rstrip()
    body = [
        GENERATED_MARKER,
        f"Source: `.pskill/skills/{skill.id}/`. This is a programmatic skill: the pskill runner gives you its steps,",
        "one at a time.",
        "",
        f"Goal: {' '.join(skill.goal.split())}",
        "",
        "1. Map the request to the inputs:" if input_lines else "1. This skill has no inputs.",
        *input_lines,
        f"2. Run: `{start_command}`",
        "   If a value has spaces, quotes, or several lines, pass `--inputs -` and give the inputs as YAML on stdin,",
        "   in the same literal form that the runner's packets show for `submit`.",
        "   Add `--mode autonomous` only when the user asked for no questions.",
        "3. The runner prints one step. Do only that step, then run the submit command at its end.",
        "   The runner checks your answer and prints the next step.",
        "4. Repeat step 3 until the runner says the run is finished. Never skip a step, and never stop before the end.",
        "   If you cannot do a step, submit only the line `$cannot_complete: <reason>`.",
        f"5. If the user asks to stop, run: `{RUNNER} pause <run-id>`. Each step names its run id.",
    ]
    return "---\n" + "\n".join(frontmatter) + "\n---\n" + "\n".join(body) + "\n"


def render_pskill_stub() -> str:
    """The built-in stub that helps the agent find, resume, and stop runs."""
    return "\n".join(
        [
            "---",
            f"name: {PSKILL_STUB_NAME}",
            'description: "Resume, inspect, pause, or cancel a pskill run (a programmatic skill run). Use when the '
            'user mentions an unfinished skill run, or asks which runs exist."',
            "---",
            GENERATED_MARKER,
            "Commands of the pskill runner:",
            f"- List the unfinished runs: `{RUNNER} runs --open`",
            f"- Show the current block of a run again: `{RUNNER} current <run-id>`",
            f"- Resume a paused run: `{RUNNER} resume <run-id>`",
            f"- Pause a run: `{RUNNER} pause <run-id>`",
            f"- Stop a run for good: `{RUNNER} cancel <run-id>`",
            f"- Open the run viewer: `{RUNNER} view`",
            "",
        ]
    )


def wanted_stubs(catalog: SkillCatalog) -> dict[str, str]:
    """Stub name -> stub text, for every skill that gets a stub, plus the pskill stub."""
    stubs = {skill.id: render_stub(skill) for skill in catalog.skills.values() if skill.invocation != "internal"}
    stubs[PSKILL_STUB_NAME] = render_pskill_stub()
    return stubs


def wanted_files(catalog: SkillCatalog) -> dict[str, str]:
    """Relative path in a stub folder (for example "review-pr/SKILL.md") -> file text."""
    files = {f"{name}/{STUB_FILE_NAME}": text for name, text in wanted_stubs(catalog).items()}
    for skill in catalog.skills.values():
        if skill.invocation == "manual":
            files[f"{skill.id}/{SIDECAR_RELATIVE_PATH}"] = SIDECAR_TEXT
    return files


def is_generated(path: Path) -> bool:
    return path.is_file() and GENERATED_MARKER_TEXT in path.read_text(encoding="utf-8")


def sync_stubs(
    project: Project, catalog: SkillCatalog, check_only: bool, protected_names: set[str] | None = None
) -> list[StubChange]:
    """Bring every stub folder in line with the skills. With check_only, report the changes only.

    `protected_names` are skills that exist but do not load right now (for example a half-edited
    skill.yaml): their stub files are neither updated nor deleted.
    """
    files = wanted_files(catalog)
    changes: list[StubChange] = []
    for folder_name in project.config.stub_folders:
        changes += stub_folder_changes(project.root / folder_name, files, protected_names or set())
    if not check_only:
        apply_stub_changes(changes, files)
    return changes


def stub_folder_changes(folder: Path, files: dict[str, str], protected_names: set[str]) -> list[StubChange]:
    changes = []
    for relative_path, text in files.items():
        path = folder / relative_path
        skill = relative_path.split("/")[0]
        if not path.exists():
            changes.append(StubChange(path, "created", skill))
        elif not is_generated(path):
            raise StubError(f"{path} is a hand-written file with the name of a pskill stub. Rename one of them.")
        elif path.read_text(encoding="utf-8") != text:
            changes.append(StubChange(path, "updated", skill))
    if folder.is_dir():
        for path in sorted([*folder.glob(f"*/{STUB_FILE_NAME}"), *folder.glob(f"*/{SIDECAR_RELATIVE_PATH}")]):
            relative_path = path.relative_to(folder).as_posix()
            skill = relative_path.split("/")[0]
            if relative_path not in files and skill not in protected_names and is_generated(path):
                changes.append(StubChange(path, "deleted", skill))
    return changes


def apply_stub_changes(changes: list[StubChange], files: dict[str, str]) -> None:
    for change in changes:
        if change.action == "deleted":
            change.path.unlink()
            remove_empty_folders(change.path.parent, stop_at_name=change.skill)
            continue
        change.path.parent.mkdir(parents=True, exist_ok=True)
        relative_path = change.path.as_posix().split(f"/{change.skill}/", 1)[1]
        change.path.write_text(files[f"{change.skill}/{relative_path}"], encoding="utf-8", newline="\n")


def remove_empty_folders(folder: Path, stop_at_name: str) -> None:
    """Remove the folder and its empty parents, up to and including the skill's stub folder."""
    while folder.is_dir() and not any(folder.iterdir()):
        folder.rmdir()
        if folder.name == stop_at_name:
            return
        folder = folder.parent
