# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Write a new pull request description, only when it differs from the current one.

Usage: uv run publish_body.py, with {"pr", "body_file"} on stdin: body_file holds the new description.
Prints {"changed"}: true when the script wrote the description. A body that differs only in its line endings or in
the whitespace at its ends is the same body, so a description that is already true stays untouched.

The Claude Code cloud GitHub proxy appends a footer to a description that a REST call writes. Both bodies lose that
exact trailing footer before the script compares them and before it writes, so a rewrite never stacks footers.

One of two identical copies, in the scripts/ folder of implement-issue and resolve-pr-feedback. Change both together:
tests/test_skill_implement_issue.py fails when they differ.
"""

import json
import re
import sys

from github_rest import gh_api

PROXY_FOOTER = re.compile(r"(?:\r?\n){2}---\r?\n_Generated by \[Claude Code\]\(https://claude\.ai/code\)_\s*\Z")


def without_proxy_footer(body: str) -> str:
    return PROXY_FOOTER.sub("", body)


def same_text(first: str, second: str) -> bool:
    return first.replace("\r\n", "\n").strip() == second.replace("\r\n", "\n").strip()


def main() -> None:
    script_input = json.load(sys.stdin)
    # newline="" keeps the line endings of the file as they are.
    with open(script_input["body_file"], encoding="utf-8", newline="") as body_file:
        body = without_proxy_footer(body_file.read())
    pull_request_path = f"repos/{{owner}}/{{repo}}/pulls/{script_input['pr']}"
    current = without_proxy_footer(gh_api(pull_request_path)["body"] or "")
    changed = not same_text(current, body)
    if changed:
        gh_api(pull_request_path, "PATCH", {"body": body})
    print(json.dumps({"changed": changed}))


if __name__ == "__main__":
    main()
