"""Codex specifics: the project hooks and command rule that pskill manages, and the Stop response.

Verified against the Codex docs and the openai/codex source on 2026-09-28:
- Hooks in `<repo>/.codex/hooks.json`, Stop output, SessionStart stdout as context, commands run in the
  session cwd (resolve paths from the git root): https://developers.openai.com/codex/hooks
- Project hooks and rules load only when the project is trusted, and each hook definition must be
  trusted once with `/hooks`: https://developers.openai.com/codex/hooks
- Command rules in `<repo>/.codex/rules/*.rules`: https://developers.openai.com/codex/rules
  Note: `decision = "allow"` runs the command outside the sandbox without prompting.
- Codex adds CODEX_THREAD_ID to every command's environment (codex-rs/core/src/exec_env.rs).
- Skills in `.agents/skills/`; `agents/openai.yaml` with `policy.allow_implicit_invocation: false`
  stops implicit use: https://developers.openai.com/codex/skills
"""

import json
from pathlib import Path
from typing import Any

from pskill_runner.hook_settings import GIT_ROOT_CODE, pskill_hooks

HOOKS_RELATIVE_PATH = Path(".codex") / "hooks.json"
RULES_RELATIVE_PATH = Path(".codex") / "rules" / "pskill.rules"
# Codex runs hooks from the session's folder, which may be a subfolder, so the root comes from git.
PROJECT_ROOT_CODE = GIT_ROOT_CODE
PSKILL_HOOKS: dict[str, dict[str, Any]] = pskill_hooks(PROJECT_ROOT_CODE, "codex")
RULES_TEXT = """\
# Generated by pskill. Do not edit. Run: uv run .pskill/pskill.py sync
# Lets the agent call the pskill runner without a prompt for every block.
prefix_rule(
    pattern = ["uv", "run", ".pskill/pskill.py"],
    decision = "allow",
    justification = "pskill: the runner of this project's programmatic skills",
    match = ["uv run .pskill/pskill.py current"],
)
"""


def sync_codex_rules(project_root: Path, check_only: bool) -> bool:
    """Write the command rule that lets the agent run pskill without asking. Return whether it changed."""
    rules_path = project_root / RULES_RELATIVE_PATH
    rules_changed = not rules_path.is_file() or rules_path.read_text(encoding="utf-8") != RULES_TEXT
    if rules_changed and not check_only:
        rules_path.parent.mkdir(parents=True, exist_ok=True)
        rules_path.write_text(RULES_TEXT, encoding="utf-8", newline="\n")
    return rules_changed


def stop_response(reason: str | None) -> tuple[str, int]:
    """Codex needs JSON on stdout. A block decision makes Codex continue, with the reason as the next prompt."""
    if reason is None:
        return "{}", 0
    return json.dumps({"decision": "block", "reason": reason}), 0
