"""Codex specifics: the project hooks and command rule that pskill manages, and the Stop response.

Verified against the Codex docs and the openai/codex source on 2026-09-28:
- Hooks in `<repo>/.codex/hooks.json`, Stop output, SessionStart stdout as context, commands run in the
  session cwd (resolve paths from the git root): https://developers.openai.com/codex/hooks
- Project hooks and rules load only when the project is trusted, and each hook definition must be
  trusted once with `/hooks`: https://developers.openai.com/codex/hooks
- Command rules in `<repo>/.codex/rules/*.rules`: https://developers.openai.com/codex/rules
  Note: `decision = "allow"` runs the command outside the sandbox without prompting.
- Codex adds CODEX_THREAD_ID to every command's environment (codex-rs/core/src/exec_env.rs).
- Skills in `.agents/skills/`; `agents/openai.yaml` with `policy.allow_implicit_invocation: false`
  stops implicit use: https://developers.openai.com/codex/skills

Verified against the openai/codex source on 2026-10-10:
- The model catalog is `models_cache.json` in the Codex folder: `$CODEX_HOME`, else `~/.codex`
  (codex-rs/models-manager/src/manager.rs, codex-rs/utils/home-dir/src/lib.rs).
- Its `models` list holds one object per model: `slug` is the name, and `upgrade` is null or an object whose
  `model` names the replacement (codex-rs/models-manager/src/cache.rs, codex-rs/protocol/src/openai_models.rs).
"""

import json
import os
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from pskill_runner.adapters import CODEX, TierRow
from pskill_runner.hook_settings import GIT_ROOT_CODE, pskill_hooks
from pskill_runner.validator import Problem

HOOKS_RELATIVE_PATH = Path(".codex") / "hooks.json"
RULES_RELATIVE_PATH = Path(".codex") / "rules" / "pskill.rules"
# Codex runs hooks from the session's folder, which may be a subfolder, so the root comes from git.
PROJECT_ROOT_CODE = GIT_ROOT_CODE
PSKILL_HOOKS: dict[str, dict[str, Any]] = pskill_hooks(PROJECT_ROOT_CODE, "codex")
RULES_TEXT = """\
# Generated by pskill. Do not edit. Run: uv run .pskill/pskill.py sync
# Lets the agent call the pskill runner without a prompt for every block.
prefix_rule(
    pattern = ["uv", "run", ".pskill/pskill.py"],
    decision = "allow",
    justification = "pskill: the runner of this project's programmatic skills",
    match = ["uv run .pskill/pskill.py current"],
)
# The strictest matching rule wins, so a runner update or install asks first: `--from` can name any URL.
prefix_rule(
    pattern = ["uv", "run", ".pskill/pskill.py", ["update", "init"]],
    decision = "prompt",
    justification = "pskill: a runner update or install changes the code that runs every skill",
    match = ["uv run .pskill/pskill.py update", "uv run .pskill/pskill.py update --from=https://example.com/pskill.zip"],
)
"""


def sync_codex_rules(project_root: Path, check_only: bool) -> bool:
    """Write the command rule that lets the agent run pskill without asking. Return whether it changed."""
    rules_path = project_root / RULES_RELATIVE_PATH
    rules_changed = not rules_path.is_file() or rules_path.read_text(encoding="utf-8") != RULES_TEXT
    if rules_changed and not check_only:
        rules_path.parent.mkdir(parents=True, exist_ok=True)
        rules_path.write_text(RULES_TEXT, encoding="utf-8", newline="\n")
    return rules_changed


def stop_response(reason: str | None) -> tuple[str, int]:
    """Codex needs JSON on stdout. A block decision makes Codex continue, with the reason as the next prompt."""
    if reason is None:
        return "{}", 0
    return json.dumps({"decision": "block", "reason": reason}), 0


def codex_home(environment: Mapping[str, str] | None = None) -> Path:
    """The Codex folder of this user: `CODEX_HOME` when it is set, else `~/.codex`."""
    environment = os.environ if environment is None else environment
    return Path(environment.get("CODEX_HOME") or Path.home() / ".codex")


def read_model_catalog(path: Path) -> dict[str, str | None] | None:
    """Each model of the Codex catalog, with the model that replaces it or None. None when there is no catalog.

    Codex rewrites this cache itself, so a file that cannot be read counts as no catalog.
    """
    try:
        catalog = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    models = catalog.get("models") if isinstance(catalog, dict) else None
    if not isinstance(models, list):
        return None
    return {
        model["slug"]: upgrade_model(model)
        for model in models
        if isinstance(model, dict) and is_text(model.get("slug"))
    }


def upgrade_model(model: dict[str, Any]) -> str | None:
    upgrade = model.get("upgrade")
    if isinstance(upgrade, dict) and is_text(upgrade.get("model")):
        return str(upgrade["model"])
    return None


def is_text(value: object) -> bool:
    return isinstance(value, str) and value != ""


def tier_model_problems(
    tiers: Mapping[str, Mapping[str, TierRow]], environment: Mapping[str, str] | None = None
) -> list[Problem]:
    """Warn on each Codex tier model that the local catalog does not list, or lists with an upgrade."""
    catalog_path = codex_home(environment) / "models_cache.json"
    catalog = read_model_catalog(catalog_path)
    if catalog is None:
        return []
    problems = []
    for tier, row in tiers.get(CODEX.name, {}).items():
        location = f"tiers.{CODEX.name}.{tier}"
        if row.model is None:
            continue
        if row.model not in catalog:
            message = f"the model {row.model!r} is not in the Codex model catalog ({catalog_path}), so Codex refuses it"
            problems.append(Problem(level="warning", location=location, message=message))
        elif catalog[row.model] is not None:
            message = f"the model {row.model!r} has an upgrade to {catalog[row.model]!r}, so Codex retires it soon"
            problems.append(Problem(level="warning", location=location, message=message))
    return problems
